# Generated by Django 4.2 on 2025-04-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='duracao',
            new_name='data_hora',
        ),
    ]
