# Generated by Django 4.2 on 2025-04-04 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('especialidade', models.CharField(choices=[('Pedriatra', 'Pediatra'), ('Médico geral', 'Médico geral'), ('Ginecologista', 'Ginecologista')], max_length=255)),
                ('crm', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('status', models.CharField(choices=[('cancelado', 'cancelado'), ('agendado', 'agendado'), ('realizado', 'realizado')], max_length=255)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
        ),
    ]
