# Generated by Django 4.2 on 2025-04-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('realizado', 'realizado'), ('cancelado', 'cancelado'), ('agendado', 'agendado')], max_length=255),
        ),
    ]
