# Generated by Django 4.2 on 2025-04-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_consulta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('agendado', 'agendado'), ('cancelado', 'cancelado'), ('realizado', 'realizado')], max_length=255),
        ),
    ]
