# Generated by Django 4.2 on 2025-04-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_alter_consulta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('cancelado', 'cancelado'), ('realizado', 'realizado'), ('agendado', 'agendado')], max_length=255),
        ),
    ]
