# Generated by Django 4.2 on 2025-04-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_alter_consulta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('realizado', 'realizado'), ('agendado', 'agendado'), ('cancelado', 'cancelado')], max_length=255),
        ),
    ]
